# Generated by Django 4.0 on 2021-12-19 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message_id',
            new_name='msg_id',
        ),
    ]
